# Use base image
FROM python:3.11-slim
RUN apt-get update && apt-get install -y ca-certificates && update-ca-certificates
# Set working directory
WORKDIR /app

# Copy code and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy everything inside backend/
COPY . .

# Tell Python where to look for modules
ENV PYTHONPATH=/app

# Run the app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
